name: Code Review with StarCoder

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history to compare with main
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          pip install replicate pygments jq

      - name: Run StarCoder Review
        run: |
          echo ">>> Scanning files for review..."
          git fetch origin main

          files=$(git diff --name-only origin/main...HEAD | grep -E '\.py$|\.js$|\.ts$|\.java$|\.cpp$|\.c$' || true)

          if [ -z "$files" ]; then
            echo "No code files to review."
            exit 0
          fi

          for file in $files; do
            echo "Reviewing: $file"
            content=$(cat "$file" | head -c 4000 | sed ':a;N;$!ba;s/\n/\\n/g')

            echo "Sending review request to Replicate API..."
            echo "File: $file"
            echo "Content preview: ${content:0:200}..."

            response=$(curl -s -X POST \
              -H "Authorization: Token ${{ secrets.REPLICATE_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "input": {
                  "prompt": "Review the following code for errors, readability, maintainability, and code smells:\n'"$content"'",
                  "temperature": 0.2,
                  "top_p": 0.95
                },
                "version": "db21e45f16ed9054c6c9adba39c3e3b90132de87f7e5ec94880c8e82cfa84717"
              }' \
              https://api.replicate.com/v1/predictions)

            echo "Full API response:"
            echo "$response" | jq '.' || echo "$response"

            echo "Parsed feedback:"
            echo "$response" | jq -r '.output[]?' || echo "No feedback received or .output is missing"
          done
